### ISSUE TITLE
Contact Request

### ISSUE THREAD

**Issue by j-schall** [Jak2k/Jak2k#2]
**Subject:** *GrapheneOS Backups (So was ähnliches wie Google One?)*
**Prefered Messenger/ Chat App**
*Check the prefered (More are better)*
- [ ] Mail
- [ ] Matrix / Element
- [x] Discord

**Comment by Jak2k** [comment]
Ich habe meinen Account bei Discord gerade re-aktiviert. Mein Name dort ist `@jak2k`.

**Comment by j-schall** [comment]
Okay, du solltest eine Freundschaftsanfrage von @appol0n bekommen haben
